" Vim color file rajalokan
" generated by VimTax http://www.vimtax.com

hi clear Normal
set bg&

hi clear

if exists("syntax_on")
  syntax reset
endif

let colors_name = "rajalokan"

hi Comment      guifg=Orange 	guibg=none 		gui=bold 	ctermfg=darkgrey 	ctermbg=none  		  cterm=none
hi Visual 	guifg=white 	guibg=darkgreen 	gui=none 	ctermfg=darkgrey  	ctermbg=white  		  cterm=none
hi Folded 	guifg=black 	guibg=lightgrey 	gui=none 	ctermfg=black  		ctermbg=darkgrey  	  cterm=none

