# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION=2

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.synced_folder "~/opt/wheelhouse/", "/home/vagrant/.wheelhouse"
  #TODO: add dotfiles too
end
