setup-bash:
	if [ -f '$(HOME)/.bashrc' ]; then \
		echo "Backing up current .bashrc to .bashrc.bak"; \
		mv $(HOME)/.bashrc $(HOME)/.bashrc.bak; \
	fi;
	if [ -f '$(HOME)/.profile' ]; then \
		echo "Backing up current .profile to .profile.bak"; \
		mv $(HOME)/.profile $(HOME)/.profile.bak; \
	fi;
	if [ -f '/etc/debian_version' ]; then \
		ln -s `pwd`/bash/bashrc_ubuntu $(HOME)/.bashrc; \
		ln -s `pwd`/bash/profile_ubuntu $(HOME)/.profile; \
	elif [ -f '/etc/redhat-release' ]; then \
		ln -s `pwd`/bash/bashrc_centos $(HOME)/.bashrc; \
		ln -s `pwd`/bash/profile_centos $(HOME)/.profile; \
	fi;
	if [ -f ${HOME}/.bash_aliases ]; then\
		echo "Backing up bash_aliases to ${HOME}/.bash_aliases.bak"; \
		mv ${HOME}/.bash_aliases ${HOME}/.bash_aliases.bak; \
	fi;
	ln -s `pwd`/bash/bash_aliases $(HOME)/.bash_aliases
	. $(HOME)/.bashrc
	echo "Successfully setup bash"

setup-vim:
	if [ ! "command -v vim > /dev/null 2>&1" && [ -f /etc/redhat-release ] ]; then\
		echo "Looks like vim is not installed. Installing vim"; \
		sudo apt-get -y install vim; \
	fi;
	if [ -f "$(HOME)/.vimrc" ]; then\
		echo "Backing up old vim configuration file vimrc"; \
		mv $(HOME)/.vimrc $(HOME)/.vimrc_bak; \
	fi;
	if [ -d "$(HOME)/.vim" ]; then\
		echo "Backing up vim conf directory"; \
		mv $(HOME)/.vim $(HOME)/.vim_bak; \
	fi;
	ln -s `pwd`/vim $(HOME)/.vim
	ln -s `pwd`/vim/vimrc $(HOME)/.vimrc
	mkdir -p `pwd`/vim/bundle
	if [ -d `pwd`/vim/bundle/Vundle.vim ]; then \
		rm -rf `pwd`/vim/bundle/Vundle.vim; \
	fi;
	git clone https://github.com/gmarik/Vundle.vim.git `pwd`/vim/bundle/Vundle.vim
	vim +PluginInstall +qall

	if [ -d "$(HOME)/.vim/.vim" ]; then\
		rm -rf $(HOME)/.vim/.vim; \
	fi;

setup-python:
	if ! type "pip" > /dev/null 2>&1; then \
		echo "Pip is not installed. Installing pip"; \
		curl -kL https://bootstrap.pypa.io/get-pip.py | sudo python; \
	fi;
	sudo pip install virtualenv virtualenvwrapper
	if [ -f /etc/redhat-release ]; then\
		echo "Installing python-devel in a RedHat machine"; \
		sudo yum -y install python-devel; \
	elif [ -f /etc/lsb-release ]; then\
		echo "Installing python-dev in a Debian machine"; \
		sudo apt-get -y install python-dev; \
	fi;
	if [ -d ${HOME}/virtualenvs/hooks ]; then \
		echo "Backign up virtualenv hooks into ${HOME}/virtualenvs/hooks_bak"; \
		mv ${HOME}/virtualenvs/hooks ${HOME}/virtualenvs/hooks.bak; \
	fi;
	mkdir -p ${HOME}/virtualenvs
	ln -s `pwd`/virtualenv/hooks ~/virtualenvs/hooks; \

setup-git:
	if ! type "git" > /dev/null 2>&1; then\
		echo "Looks like git is not installed. Installing git"; \
		sudo apt-get -y install git; \
	fi;
	if [ -f $(HOME)/.gitconfig ]; then \
		echo "Backing up current $(HOME)/.gitconfig to $(HOME)/.gitconfig.bak"; \
		mv $(HOME)/.gitconfig $(HOME)/.gitconfig.bak; \
	fi;
	ln -s `pwd`/git/gitconfig ~/.gitconfig
	ln -s `pwd`/git/gitignore ~/.gitignore

setup-tmux:
	if ! type "tmux" > /dev/null 2>&1 ; then\
		echo "Looks like tmux is not installed. Installing tmux"; \
		sudo apt-get -y install tmux; \
	fi;
	if [ -f $(HOME)/.tmux.conf ]; then \
		echo "Backing up current tmux config to $(HOME)/.tmux.conf.bak"; \
		mv $(HOME)/.tmux.conf $(HOME)/.tmux.conf.bak; \
	fi;
	ln -s `pwd`/tmux/tmux.conf ~/.tmux.conf

setup-vrapper:
	ln -s `pwd`/vrapper/vrapperrc ~/.vrapperrc

setup-vagrant:
	if [ -f "${HOME}/.vagrant.d/Vagrantfile" ]; then \
		echo "Global Vagrant file already exist. Backing it to ${HOME}/.vagrant.d/Vagrantfile.bak"; \
		mv ${HOME}/.vagrant.d/Vagrantfile ${HOME}/.vagrant.d/Vagrantfile.bak; \
	fi;
	ln -s `pwd`/vagrant/Vagrantfile ${HOME}/.vagrant.d/Vagrantfile
